/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V86RouteRouteImport } from './routes/v86/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V86IndexRouteImport } from './routes/v86/index'
import { Route as V86Regel5RouteImport } from './routes/v86/regel-5'
import { Route as V86Regel4RouteImport } from './routes/v86/regel-4'
import { Route as V86Regel3RouteImport } from './routes/v86/regel-3'
import { Route as V86Regel2RouteImport } from './routes/v86/regel-2'
import { Route as V86Regel1RouteImport } from './routes/v86/regel-1'
import { Route as ApiPredictRouteImport } from './routes/api/predict'

const V86RouteRoute = V86RouteRouteImport.update({
  id: '/v86',
  path: '/v86',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V86IndexRoute = V86IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V86RouteRoute,
} as any)
const V86Regel5Route = V86Regel5RouteImport.update({
  id: '/regel-5',
  path: '/regel-5',
  getParentRoute: () => V86RouteRoute,
} as any)
const V86Regel4Route = V86Regel4RouteImport.update({
  id: '/regel-4',
  path: '/regel-4',
  getParentRoute: () => V86RouteRoute,
} as any)
const V86Regel3Route = V86Regel3RouteImport.update({
  id: '/regel-3',
  path: '/regel-3',
  getParentRoute: () => V86RouteRoute,
} as any)
const V86Regel2Route = V86Regel2RouteImport.update({
  id: '/regel-2',
  path: '/regel-2',
  getParentRoute: () => V86RouteRoute,
} as any)
const V86Regel1Route = V86Regel1RouteImport.update({
  id: '/regel-1',
  path: '/regel-1',
  getParentRoute: () => V86RouteRoute,
} as any)
const ApiPredictRoute = ApiPredictRouteImport.update({
  id: '/api/predict',
  path: '/api/predict',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/v86': typeof V86RouteRouteWithChildren
  '/api/predict': typeof ApiPredictRoute
  '/v86/regel-1': typeof V86Regel1Route
  '/v86/regel-2': typeof V86Regel2Route
  '/v86/regel-3': typeof V86Regel3Route
  '/v86/regel-4': typeof V86Regel4Route
  '/v86/regel-5': typeof V86Regel5Route
  '/v86/': typeof V86IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/predict': typeof ApiPredictRoute
  '/v86/regel-1': typeof V86Regel1Route
  '/v86/regel-2': typeof V86Regel2Route
  '/v86/regel-3': typeof V86Regel3Route
  '/v86/regel-4': typeof V86Regel4Route
  '/v86/regel-5': typeof V86Regel5Route
  '/v86': typeof V86IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/v86': typeof V86RouteRouteWithChildren
  '/api/predict': typeof ApiPredictRoute
  '/v86/regel-1': typeof V86Regel1Route
  '/v86/regel-2': typeof V86Regel2Route
  '/v86/regel-3': typeof V86Regel3Route
  '/v86/regel-4': typeof V86Regel4Route
  '/v86/regel-5': typeof V86Regel5Route
  '/v86/': typeof V86IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/v86'
    | '/api/predict'
    | '/v86/regel-1'
    | '/v86/regel-2'
    | '/v86/regel-3'
    | '/v86/regel-4'
    | '/v86/regel-5'
    | '/v86/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/predict'
    | '/v86/regel-1'
    | '/v86/regel-2'
    | '/v86/regel-3'
    | '/v86/regel-4'
    | '/v86/regel-5'
    | '/v86'
  id:
    | '__root__'
    | '/'
    | '/v86'
    | '/api/predict'
    | '/v86/regel-1'
    | '/v86/regel-2'
    | '/v86/regel-3'
    | '/v86/regel-4'
    | '/v86/regel-5'
    | '/v86/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  V86RouteRoute: typeof V86RouteRouteWithChildren
  ApiPredictRoute: typeof ApiPredictRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v86': {
      id: '/v86'
      path: '/v86'
      fullPath: '/v86'
      preLoaderRoute: typeof V86RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v86/': {
      id: '/v86/'
      path: '/'
      fullPath: '/v86/'
      preLoaderRoute: typeof V86IndexRouteImport
      parentRoute: typeof V86RouteRoute
    }
    '/v86/regel-5': {
      id: '/v86/regel-5'
      path: '/regel-5'
      fullPath: '/v86/regel-5'
      preLoaderRoute: typeof V86Regel5RouteImport
      parentRoute: typeof V86RouteRoute
    }
    '/v86/regel-4': {
      id: '/v86/regel-4'
      path: '/regel-4'
      fullPath: '/v86/regel-4'
      preLoaderRoute: typeof V86Regel4RouteImport
      parentRoute: typeof V86RouteRoute
    }
    '/v86/regel-3': {
      id: '/v86/regel-3'
      path: '/regel-3'
      fullPath: '/v86/regel-3'
      preLoaderRoute: typeof V86Regel3RouteImport
      parentRoute: typeof V86RouteRoute
    }
    '/v86/regel-2': {
      id: '/v86/regel-2'
      path: '/regel-2'
      fullPath: '/v86/regel-2'
      preLoaderRoute: typeof V86Regel2RouteImport
      parentRoute: typeof V86RouteRoute
    }
    '/v86/regel-1': {
      id: '/v86/regel-1'
      path: '/regel-1'
      fullPath: '/v86/regel-1'
      preLoaderRoute: typeof V86Regel1RouteImport
      parentRoute: typeof V86RouteRoute
    }
    '/api/predict': {
      id: '/api/predict'
      path: '/api/predict'
      fullPath: '/api/predict'
      preLoaderRoute: typeof ApiPredictRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface V86RouteRouteChildren {
  V86Regel1Route: typeof V86Regel1Route
  V86Regel2Route: typeof V86Regel2Route
  V86Regel3Route: typeof V86Regel3Route
  V86Regel4Route: typeof V86Regel4Route
  V86Regel5Route: typeof V86Regel5Route
  V86IndexRoute: typeof V86IndexRoute
}

const V86RouteRouteChildren: V86RouteRouteChildren = {
  V86Regel1Route: V86Regel1Route,
  V86Regel2Route: V86Regel2Route,
  V86Regel3Route: V86Regel3Route,
  V86Regel4Route: V86Regel4Route,
  V86Regel5Route: V86Regel5Route,
  V86IndexRoute: V86IndexRoute,
}

const V86RouteRouteWithChildren = V86RouteRoute._addFileChildren(
  V86RouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  V86RouteRoute: V86RouteRouteWithChildren,
  ApiPredictRoute: ApiPredictRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
